##### Theme

# -------------------------------
# --> Kanagawa (Wave)
thm_bg="#2a2a37"  # Kanagawa Wave surface_1
thm_fg="#dcd7ba"  # Kanagawa Wave foreground

## -------------------------------
## Accent colors
thm_sakura="#f6c6b8"  # Kanagawa sakura (rosewater)
thm_ume="#e46876"      # Kanagawa ume (flamingo)
thm_pink="#ffa0c3"     # Kanagawa pink
thm_murasaki="#a3a9ce" # Kanagawa murasaki (mauve)
thm_akane="#c34043"    # Kanagawa akane (red)
thm_kuri="#b4637a"     # Kanagawa kuri (maroon)
thm_mikan="#ffa066"    # Kanagawa mikan (peach)
thm_kohaku="#e6c384"   # Kanagawa kohaku (yellow)
thm_midori="#76946a"   # Kanagawa midori (green)
thm_aoi="#7fb4ca"      # Kanagawa aoi (teal)
thm_sora="#7e9cd8"     # Kanagawa sora (sky)
thm_ruri="#6a9589"     # Kanagawa ruri (sapphire)
thm_ao="#658594"       # Kanagawa ao (blue)
thm_shiro="#c8c093"    # Kanagawa shiro (lavender)

## -------------------------------
## Surfaces and overlays
thm_subtext_1="#938aa9"  # Kanagawa subtext_1
thm_subtext_0="#c8c093"  # Kanagawa subtext_0
thm_overlay_2="#727169"  # Kanagawa overlay_2
thm_overlay_1="#565575"  # Kanagawa overlay_1
thm_overlay_0="#393838"  # Kanagawa overlay_0
thm_surface_2="#223249"  # Kanagawa surface_2
thm_surface_1="#2a2a37"  # Kanagawa surface_1
thm_surface_0="#363646"  # Kanagawa surface_0
thm_base="#1f1f28"       # Kanagawa base
thm_mantle="#16161d"     # Kanagawa mantle
thm_crust="#0f0f15"      # Kanagawa crust

## -------------------------------
## Custom vars for easy tweaks

thm_active="${thm_bg}"
thm_inactive="${thm_bg}"

thm_active_fg="${thm_murasaki}"
thm_inactive_fg="${thm_overlay_0}"

thm_pane_active="${thm_murasaki}"
thm_pane_inactive="${thm_bg}"

thm_msg_bg="${thm_murasaki}"
thm_msg_fg="${thm_crust}"

thm_win_active="${thm_bg}"
thm_win_inactive="${thm_bg}"

thm_win_active_fg="${thm_murasaki}"
thm_win_inactive_fg="${thm_overlay_2}"

