# ------ #
# Styles #
# ------ #

# PANE & BORDER DESIGN

# Pane borders
set -g pane-border-style "fg=$sumiInk4"
set -g pane-active-border-style "fg=$crystalBlue"

# Message text (Command mode)
set -g message-style "bg=$oniViolet,fg=$sumiInk3,bold"

# STATUS BAR DESIGN (Rounded Aesthetic)
set -g status-justify left
set -g status-position top
set -g status-style "bg=default,fg=$fujiWhite" # Background 'default' for transparency

# --- LEFT SIDE ---
set -g status-left " "

# --- WINDOW TABS ---
setw -g window-status-separator " "

# Active Window (Pill shape)
setw -g window-status-current-format "#[fg=$crystalBlue,bg=default]#[fg=$sumiInk0,bg=$crystalBlue,bold]#I:#W#{?window_zoomed_flag, 󰋱,}#[fg=$crystalBlue,bg=default]"
setw -g window-status-format "#[fg=$sumiInk5,bg=default]#[fg=$sumiInk4,bg=$sumiInk5,bold]#I:#W#[fg=$sumiInk5,bg=default]"

# --- RIGHT SIDE: Hardware ---
set -g status-right-length 150
set -g status-right "#[fg=$crystalBlue,bg=default]#[fg=$sumiInk0,bg=$crystalBlue,bold] #{window_panes}#[fg=$crystalBlue,bg=default] #[fg=$oniViolet,bg=default]#[fg=$sumiInk0,bg=$oniViolet,bold] #(top -bn1 | grep 'Cpu(s)' | awk '{print $2}')%#[fg=$oniViolet,bg=default] #[fg=$springGreen,bg=default]#[fg=$sumiInk0,bg=$springGreen,bold]  #(free -h | awk '/^Mem:/ {print $3}')#[fg=$springGreen,bg=default] "

