## Base
source-file "$HOME/.config/tmux/base/plugins.conf"
source-file "$HOME/.config/tmux/base/keymaps.conf"
source-file "$HOME/.config/tmux/base/options.conf"

## Theme (swap the source line to change palette)
source-file "$HOME/.config/tmux/themes/kanagawa.conf"
# source-file "$HOME/.config/tmux/themes/everforest.conf"

## Layout (swap the source line to change status-bar look)
source-file "$HOME/.config/tmux/layouts/classic.conf"
# source-file "$HOME/.config/tmux/layouts/bubble.conf"
