# Auto-install TPM if not present
if-shell "test ! -d ~/.tmux/plugins/tpm" \
   "run-shell 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# List of plugins

## Utils
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

## UI
set -g @plugin 'sainnhe/tmux-fzf'

# Initialize TMUX plugin manager (keep at bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
